### ISSUE TITLE
CSS Baseline

### ISSUE THREAD

**Issue by GYF1** [GYF1/GYF1.github.io#11]
# 起因
```css
* {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    .container {
      width: 1200px;
      margin: 0 auto;
      height: 100px;
      font-size: 0;
    }

    .left1 {
      width: 200px;
      height: 100px;
      background-color: #eee;
      display: inline-block;
      /*font-size: 10px;*/
    }

    .right1 {
      background-color: #333;
      color: #fff;
      height: 100px;
      width: calc(100% - 200px);
      display: inline-block;
      font-size: 16px;
    }
```
```html
<div class="container">
  <div class="left1">
  </div>
  <div class="right1">
    world
  </div>
</div>
```

本来设想left1和right1显示在同一行，但是事与愿违。最终发现baseline是问题所在。
