### ISSUE TITLE
宽度自动拓展

### ISSUE THREAD

**Issue by GYF1** [GYF1/GYF1.github.io#13]
标题想表达的意思是：假如页面有两列，一列的宽度固定，另一列的宽度自动拓展剩下的宽度。

因为实现的方法众多，所以想整理下

# calc
通过width: calc(100% - 200px)
对低版本支持的不好

# float + overflow
假如右列固定，左列宽度自动拓展
```css
.container {
    width:600px;
    height:200px;
    border:1px solid;
}
.left {
    width:auto;
    height:200px;
    background:red;
    overflow:hidden;
}
.right {
    height:200px;
    width:200px;
    background:blue;
    float:right;
}
```
```html
<div class="container">
    <div class="right"></div>
    <div class="left"></div>
</div>
```
需要注意的地方:
右列有float
左列有overflow
div的顺序是先right后left

三个注意点，错一个都实现不了
